### ISSUE TITLE
Config: "regexplist" and "unregexplist" statements do not work

### ISSUE THREAD

**Issue by cbuijs** [Carpetsmoker/trackwall#2]
Using:

```
regexplist plain file:///regexp.list
unregexplist plain file:///regexp.list
```

Resulting in following errors:

```
error parsing regexplists/unregexplists: don't know how to set fields of the type [][]string
```

The non-list versions ("regexp" and "unregexp") work fine.

Seems that "cfg.go" is missing code and config.go needs some work too (I am not an expert at all).

**Comment by Carpetsmoker** [comment]
I either never implemented this, or it got lost at some point. I fixed it now!

By the way, a word of warning: in general trackwall works very well and I use it on all my computers,this is very much "experimental" software, and some rough edges (mostly relating to the UI). I really need to spend some time to finish it properly some day.

**Comment by cbuijs** [comment]
@Carpetsmoker awesome-sauce! I will test it.

Yeah, I saw the disclaimer as well, but seems to be pretty stable here for weeks, and it is not running on anything trivial.

Thanks again!

**Comment by cbuijs** [comment]
@Carpetsmoker 

Nope. Still does not work. Same errors. See a full line from log:

```
trackwall -vv -c /etc/trackwall/config server
error root.go:50 cannot load config: /etc/trackwall/config line 74: error parsing regexplist: don't know how to set fields of the type [][]string
```
I use following lines in /etc/trackwall/config:

```
regexplist plain file:///regexp.list
unregexplist plain file:///unregexp.list
```

The list files just contain 1 line each for testing purposes. They are located in the chroot directory.

regexp.list:
`^ad[sz]+?[0-9]+?\.`

unregexp.list:
`^account\.`

Hope this helps and I am not too much of a bother. I have a workaround by putting everything in separate config files and "include" them in the main config.

-Chris

**Comment by Carpetsmoker** [comment]
Maybe you either didn't recompile it correctly, or maybe you're running the wrong `trackwall` binary? How did you recompile it, and what does `which trackwall` say?

> Hope this helps and I am not too much of a bother.

No, that's fine. FIxiing bugs is always good! :-)

**Comment by cbuijs** [comment]
@Carpetsmoker 

```
which trackwall
/usr/local/sbin/trackwall
```
And it is the correct one (file-date/time updated). Also checked the patches and they are there in the local version I build from (after download).

Also run the binary directly from build directory with same issue/error.

Old/New version of the bin say both "0.1" when doing a "version" command. Might need to update that to make troubleshooting on this kind of stuff more handy ;-).

-Chris.

**Comment by Carpetsmoker** [comment]
I just tested here again, and it really does seem to work.

I just updated the version to `0.2`, so if after updating again you still get `0.1` then you know for sure you've got an old binary ;-)

**Comment by cbuijs** [comment]
@Carpetsmoker 

Boomshakalaka! Works!

This time I started from scratch and made sure everything was removed/cleaned-up and did a `go get` instead of downloading the github repo locally and `go build` it. That might be what was wrong... maybe...

```
/usr/local/sbin/trackwall version
0.2
```
And running:
```
/usr/local/sbin/trackwall -vv -c /etc/trackwall/config server
info helper.go:32         chrooting to /var/trackwall
info config.go:86         reading compiled list from /cache/compiled
info server.go:69         initialisation finished; ready to serve
```
Thanks so much, you rock!

-Chris.
